package com.mit.entity;

// Generated 9 juin 2016 18:19:25 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Archmemb generated by hbm2java
 */
@Entity
@Table(name = "archmemb", catalog = "mitdb")
public class Archmemb implements java.io.Serializable {

	private int cin;
	private String email;
	private String nom;
	private String prenom;
	private String adr;
	private int tel;
	private String password;
	private int idCv;

	public Archmemb() {
	}

	public Archmemb(int cin, String email, String nom, String prenom,
			String adr, int tel, String password, int idCv) {
		this.cin = cin;
		this.email = email;
		this.nom = nom;
		this.prenom = prenom;
		this.adr = adr;
		this.tel = tel;
		this.password = password;
		this.idCv = idCv;
	}

	@Id
	@Column(name = "cin", unique = true, nullable = false)
	public int getCin() {
		return this.cin;
	}

	public void setCin(int cin) {
		this.cin = cin;
	}

	@Column(name = "email", nullable = false, length = 254)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "nom", nullable = false, length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false, length = 254)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "adr", nullable = false, length = 254)
	public String getAdr() {
		return this.adr;
	}

	public void setAdr(String adr) {
		this.adr = adr;
	}

	@Column(name = "tel", nullable = false)
	public int getTel() {
		return this.tel;
	}

	public void setTel(int tel) {
		this.tel = tel;
	}

	@Column(name = "password", nullable = false, length = 254)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "idCv", nullable = false)
	public int getIdCv() {
		return this.idCv;
	}

	public void setIdCv(int idCv) {
		this.idCv = idCv;
	}

}
