package com.mit.entity;

// Generated 9 juin 2016 18:19:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Attestation generated by hbm2java
 */
@Entity
@Table(name = "attestation", catalog = "mitdb")
public class Attestation implements java.io.Serializable {

	private AttestationId id;
	private Membre membre;
	private Projet projet;
	private Date dateDebut;
	private Date dateFin;

	public Attestation() {
	}

	public Attestation(AttestationId id, Membre membre, Projet projet) {
		this.id = id;
		this.membre = membre;
		this.projet = projet;
	}

	public Attestation(AttestationId id, Membre membre, Projet projet,
			Date dateDebut, Date dateFin) {
		this.id = id;
		this.membre = membre;
		this.projet = projet;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cin", column = @Column(name = "cin", nullable = false)),
			@AttributeOverride(name = "idProjet", column = @Column(name = "idProjet", nullable = false)),
			@AttributeOverride(name = "idAttestation", column = @Column(name = "idAttestation", nullable = false)) })
	public AttestationId getId() {
		return this.id;
	}

	public void setId(AttestationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cin", nullable = false, insertable = false, updatable = false)
	public Membre getMembre() {
		return this.membre;
	}

	public void setMembre(Membre membre) {
		this.membre = membre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idProjet", nullable = false, insertable = false, updatable = false)
	public Projet getProjet() {
		return this.projet;
	}

	public void setProjet(Projet projet) {
		this.projet = projet;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateDebut", length = 10)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateFin", length = 10)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

}
