package com.mit.entity;

// Generated 9 juin 2016 18:19:25 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Competance generated by hbm2java
 */
@Entity
@Table(name = "competance", catalog = "mitdb")
public class Competance implements java.io.Serializable {

	private Integer idCompetance;
	private String nomCompetance;
	private Set<Cv> cvs = new HashSet<Cv>(0);

	public Competance() {
	}

	public Competance(String nomCompetance, Set<Cv> cvs) {
		this.nomCompetance = nomCompetance;
		this.cvs = cvs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCompetance", unique = true, nullable = false)
	public Integer getIdCompetance() {
		return this.idCompetance;
	}

	public void setIdCompetance(Integer idCompetance) {
		this.idCompetance = idCompetance;
	}

	@Column(name = "nomCompetance", length = 254)
	public String getNomCompetance() {
		return this.nomCompetance;
	}

	public void setNomCompetance(String nomCompetance) {
		this.nomCompetance = nomCompetance;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "compcv", catalog = "mitdb", joinColumns = { @JoinColumn(name = "idCompetance", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "idCv", nullable = false, updatable = false) })
	public Set<Cv> getCvs() {
		return this.cvs;
	}

	public void setCvs(Set<Cv> cvs) {
		this.cvs = cvs;
	}

}
