package com.mit.entity;

// Generated 9 juin 2016 18:19:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contratsociete generated by hbm2java
 */
@Entity
@Table(name = "contratsociete", catalog = "mitdb")
public class Contratsociete implements java.io.Serializable {

	private ContratsocieteId id;
	private Societe societe;
	private Projet projet;
	private Integer coutPayer;
	private Date dateContrat;
	private Date debutContrat;
	private Date finContrat;

	public Contratsociete() {
	}

	public Contratsociete(ContratsocieteId id, Societe societe, Projet projet,
			Date dateContrat, Date debutContrat, Date finContrat) {
		this.id = id;
		this.societe = societe;
		this.projet = projet;
		this.dateContrat = dateContrat;
		this.debutContrat = debutContrat;
		this.finContrat = finContrat;
	}

	public Contratsociete(ContratsocieteId id, Societe societe, Projet projet,
			Integer coutPayer, Date dateContrat, Date debutContrat,
			Date finContrat) {
		this.id = id;
		this.societe = societe;
		this.projet = projet;
		this.coutPayer = coutPayer;
		this.dateContrat = dateContrat;
		this.debutContrat = debutContrat;
		this.finContrat = finContrat;
	}
	
	

	public Contratsociete(ContratsocieteId id, Societe societe, Projet projet) {
		super();
		this.id = id;
		this.societe = societe;
		this.projet = projet;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idProjet", column = @Column(name = "idProjet", nullable = false)),
			@AttributeOverride(name = "idContrat", column = @Column(name = "idContrat", nullable = false)),
			@AttributeOverride(name = "idSociete", column = @Column(name = "idSociete", nullable = false)) })
	public ContratsocieteId getId() {
		return this.id;
	}

	public void setId(ContratsocieteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSociete", nullable = false, insertable = false, updatable = false)
	public Societe getSociete() {
		return this.societe;
	}

	public void setSociete(Societe societe) {
		this.societe = societe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idProjet", nullable = false, insertable = false, updatable = false)
	public Projet getProjet() {
		return this.projet;
	}

	public void setProjet(Projet projet) {
		this.projet = projet;
	}

	@Column(name = "coutPayer", precision = 8, scale = 0)
	public Integer getCoutPayer() {
		return this.coutPayer;
	}

	public void setCoutPayer(Integer coutPayer) {
		this.coutPayer = coutPayer;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateContrat", nullable = false, length = 10)
	public Date getDateContrat() {
		return this.dateContrat;
	}

	public void setDateContrat(Date dateContrat) {
		this.dateContrat = dateContrat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "debutContrat", nullable = false, length = 10)
	public Date getDebutContrat() {
		return this.debutContrat;
	}

	public void setDebutContrat(Date debutContrat) {
		this.debutContrat = debutContrat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "finContrat", nullable = false, length = 10)
	public Date getFinContrat() {
		return this.finContrat;
	}

	public void setFinContrat(Date finContrat) {
		this.finContrat = finContrat;
	}

}
