package com.mit.entity;

// Generated 9 juin 2016 18:19:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contrat generated by hbm2java
 */
@Entity
@Table(name = "contrat", catalog = "mitdb")
public class Contrat implements java.io.Serializable {

	private Integer idContrat;
	private Date dateContrat;
	private Date debutContrat;
	private Date finContrat;

	public Contrat() {
	}

	public Contrat(Date dateContrat, Date debutContrat, Date finContrat) {
		this.dateContrat = dateContrat;
		this.debutContrat = debutContrat;
		this.finContrat = finContrat;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idContrat", unique = true, nullable = false)
	public Integer getIdContrat() {
		return this.idContrat;
	}

	public void setIdContrat(Integer idContrat) {
		this.idContrat = idContrat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateContrat", length = 10)
	public Date getDateContrat() {
		return this.dateContrat;
	}

	public void setDateContrat(Date dateContrat) {
		this.dateContrat = dateContrat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "debutContrat", length = 10)
	public Date getDebutContrat() {
		return this.debutContrat;
	}

	public void setDebutContrat(Date debutContrat) {
		this.debutContrat = debutContrat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "finContrat", length = 10)
	public Date getFinContrat() {
		return this.finContrat;
	}

	public void setFinContrat(Date finContrat) {
		this.finContrat = finContrat;
	}

}
