package com.mit.entity;

// Generated 9 juin 2016 18:19:25 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContratmembreId generated by hbm2java
 */
@Embeddable
public class ContratmembreId implements java.io.Serializable {

	private int cin;
	private int idProjet;
	private int idTache;
	private int idContrat;

	public ContratmembreId() {
	}

	public ContratmembreId(int cin, int idProjet, int idTache, int idContrat) {
		this.cin = cin;
		this.idProjet = idProjet;
		this.idTache = idTache;
		this.idContrat = idContrat;
	}

	@Column(name = "cin", nullable = false)
	public int getCin() {
		return this.cin;
	}

	public void setCin(int cin) {
		this.cin = cin;
	}

	@Column(name = "idProjet", nullable = false)
	public int getIdProjet() {
		return this.idProjet;
	}

	public void setIdProjet(int idProjet) {
		this.idProjet = idProjet;
	}

	@Column(name = "idTache", nullable = false)
	public int getIdTache() {
		return this.idTache;
	}

	public void setIdTache(int idTache) {
		this.idTache = idTache;
	}

	@Column(name = "idContrat", nullable = false)
	public int getIdContrat() {
		return this.idContrat;
	}

	public void setIdContrat(int idContrat) {
		this.idContrat = idContrat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContratmembreId))
			return false;
		ContratmembreId castOther = (ContratmembreId) other;

		return (this.getCin() == castOther.getCin())
				&& (this.getIdProjet() == castOther.getIdProjet())
				&& (this.getIdTache() == castOther.getIdTache())
				&& (this.getIdContrat() == castOther.getIdContrat());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCin();
		result = 37 * result + this.getIdProjet();
		result = 37 * result + this.getIdTache();
		result = 37 * result + this.getIdContrat();
		return result;
	}

}
