package com.mit.entity;

// Generated 9 juin 2016 18:19:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cv generated by hbm2java
 */
@Entity
@Table(name = "cv", catalog = "mitdb")
public class Cv implements java.io.Serializable {

	private Integer idCv;
	private Membre membre;
	private Date dateCv;
	private Set<Diplome> diplomes = new HashSet<Diplome>(0);
	private Set<Experience> experiences = new HashSet<Experience>(0);
	private Set<Competance> competances = new HashSet<Competance>(0);
	private Set<Membre> membres = new HashSet<Membre>(0);

	public Cv() {
	}

	public Cv(Membre membre, Date dateCv) {
		this.membre = membre;
		this.dateCv = dateCv;
	}

	public Cv(Membre membre, Date dateCv, Set<Diplome> diplomes,
			Set<Experience> experiences, Set<Competance> competances,
			Set<Membre> membres) {
		this.membre = membre;
		this.dateCv = dateCv;
		this.diplomes = diplomes;
		this.experiences = experiences;
		this.competances = competances;
		this.membres = membres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCv", unique = true, nullable = false)
	public Integer getIdCv() {
		return this.idCv;
	}

	public void setIdCv(Integer idCv) {
		this.idCv = idCv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cin", nullable = false)
	public Membre getMembre() {
		return this.membre;
	}

	public void setMembre(Membre membre) {
		this.membre = membre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCv", nullable = false, length = 10)
	public Date getDateCv() {
		return this.dateCv;
	}

	public void setDateCv(Date dateCv) {
		this.dateCv = dateCv;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cv")
	public Set<Diplome> getDiplomes() {
		return this.diplomes;
	}

	public void setDiplomes(Set<Diplome> diplomes) {
		this.diplomes = diplomes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cv")
	public Set<Experience> getExperiences() {
		return this.experiences;
	}

	public void setExperiences(Set<Experience> experiences) {
		this.experiences = experiences;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "cvs")
	public Set<Competance> getCompetances() {
		return this.competances;
	}

	public void setCompetances(Set<Competance> competances) {
		this.competances = competances;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cv")
	public Set<Membre> getMembres() {
		return this.membres;
	}

	public void setMembres(Set<Membre> membres) {
		this.membres = membres;
	}

}
