package com.mit.entity;

// Generated 9 juin 2016 18:19:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Diplome generated by hbm2java
 */
@Entity
@Table(name = "diplome", catalog = "mitdb")
public class Diplome implements java.io.Serializable {

	private Integer idDip;
	private Etablissement etablissement;
	private Cv cv;
	private String typeDip;
	private Date dateObtention;

	public Diplome() {
	}

	public Diplome(Etablissement etablissement, Cv cv, String typeDip,
			Date dateObtention) {
		this.etablissement = etablissement;
		this.cv = cv;
		this.typeDip = typeDip;
		this.dateObtention = dateObtention;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDip", unique = true, nullable = false)
	public Integer getIdDip() {
		return this.idDip;
	}

	public void setIdDip(Integer idDip) {
		this.idDip = idDip;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEtab")
	public Etablissement getEtablissement() {
		return this.etablissement;
	}

	public void setEtablissement(Etablissement etablissement) {
		this.etablissement = etablissement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCv")
	public Cv getCv() {
		return this.cv;
	}

	public void setCv(Cv cv) {
		this.cv = cv;
	}

	@Column(name = "typeDip", length = 254)
	public String getTypeDip() {
		return this.typeDip;
	}

	public void setTypeDip(String typeDip) {
		this.typeDip = typeDip;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateObtention", length = 10)
	public Date getDateObtention() {
		return this.dateObtention;
	}

	public void setDateObtention(Date dateObtention) {
		this.dateObtention = dateObtention;
	}

}
