package com.mit.entity;

// Generated 9 juin 2016 18:19:25 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Membre generated by hbm2java
 */
@Entity
@Table(name = "membre", catalog = "mitdb")
public class Membre implements java.io.Serializable {

	private int cin;
	private Cv cv;
	private String email;
	private String nom;
	private String prenom;
	private String adr;
	private Integer tel;
	private String password;
	private Set<Cv> cvs = new HashSet<Cv>(0);
	private Set<Contratmembre> contratmembres = new HashSet<Contratmembre>(0);
	private Set<Attestation> attestations = new HashSet<Attestation>(0);
	private Set<Pvreunion> pvreunions = new HashSet<Pvreunion>(0);

	public Membre() {
	}

	public Membre(int cin) {
		this.cin = cin;
	}

	public Membre(int cin, Cv cv, String email, String nom, String prenom,
			String adr, Integer tel, String password, Set<Cv> cvs,
			Set<Contratmembre> contratmembres, Set<Attestation> attestations,
			Set<Pvreunion> pvreunions) {
		this.cin = cin;
		this.cv = cv;
		this.email = email;
		this.nom = nom;
		this.prenom = prenom;
		this.adr = adr;
		this.tel = tel;
		this.password = password;
		this.cvs = cvs;
		this.contratmembres = contratmembres;
		this.attestations = attestations;
		this.pvreunions = pvreunions;
	}

	@Id
	@Column(name = "cin", unique = true, nullable = false)
	public int getCin() {
		return this.cin;
	}

	public void setCin(int cin) {
		this.cin = cin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCv")
	public Cv getCv() {
		return this.cv;
	}

	public void setCv(Cv cv) {
		this.cv = cv;
	}

	@Column(name = "email", length = 254)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 254)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "adr", length = 254)
	public String getAdr() {
		return this.adr;
	}

	public void setAdr(String adr) {
		this.adr = adr;
	}

	@Column(name = "tel")
	public Integer getTel() {
		return this.tel;
	}

	public void setTel(Integer tel) {
		this.tel = tel;
	}

	@Column(name = "password", length = 254)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "membre")
	public Set<Cv> getCvs() {
		return this.cvs;
	}

	public void setCvs(Set<Cv> cvs) {
		this.cvs = cvs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "membre")
	public Set<Contratmembre> getContratmembres() {
		return this.contratmembres;
	}

	public void setContratmembres(Set<Contratmembre> contratmembres) {
		this.contratmembres = contratmembres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "membre")
	public Set<Attestation> getAttestations() {
		return this.attestations;
	}

	public void setAttestations(Set<Attestation> attestations) {
		this.attestations = attestations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "membre")
	public Set<Pvreunion> getPvreunions() {
		return this.pvreunions;
	}

	public void setPvreunions(Set<Pvreunion> pvreunions) {
		this.pvreunions = pvreunions;
	}

}
