package com.mit.entity;

// Generated 9 juin 2016 18:19:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Projet generated by hbm2java
 */
@Entity
@Table(name = "projet", catalog = "mitdb")
public class Projet implements java.io.Serializable {

	private Integer idProjet;
	private String titreProjet;
	private String descProjet;
	private Date dateDebut;
	private Date dateFin;
	private Set<Attestation> attestations = new HashSet<Attestation>(0);
	private Set<Tache> taches = new HashSet<Tache>(0);
	private Set<Pvreunion> pvreunions = new HashSet<Pvreunion>(0);
	private Set<Contratsociete> contratsocietes = new HashSet<Contratsociete>(0);

	public Projet() {
	}

	public Projet(String titreProjet) {
		this.titreProjet = titreProjet;
	}

	public Projet(String titreProjet, String descProjet, Date dateDebut,
			Date dateFin, Set<Attestation> attestations, Set<Tache> taches,
			Set<Pvreunion> pvreunions, Set<Contratsociete> contratsocietes) {
		this.titreProjet = titreProjet;
		this.descProjet = descProjet;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.attestations = attestations;
		this.taches = taches;
		this.pvreunions = pvreunions;
		this.contratsocietes = contratsocietes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idProjet", unique = true, nullable = false)
	public Integer getIdProjet() {
		return this.idProjet;
	}

	public void setIdProjet(Integer idProjet) {
		this.idProjet = idProjet;
	}

	@Column(name = "titreProjet", nullable = false, length = 254)
	public String getTitreProjet() {
		return this.titreProjet;
	}

	public void setTitreProjet(String titreProjet) {
		this.titreProjet = titreProjet;
	}

	@Column(name = "descProjet", length = 254)
	public String getDescProjet() {
		return this.descProjet;
	}

	public void setDescProjet(String descProjet) {
		this.descProjet = descProjet;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateDebut", length = 10)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateFin", length = 10)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projet")
	public Set<Attestation> getAttestations() {
		return this.attestations;
	}

	public void setAttestations(Set<Attestation> attestations) {
		this.attestations = attestations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projet")
	public Set<Tache> getTaches() {
		return this.taches;
	}

	public void setTaches(Set<Tache> taches) {
		this.taches = taches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projet")
	public Set<Pvreunion> getPvreunions() {
		return this.pvreunions;
	}

	public void setPvreunions(Set<Pvreunion> pvreunions) {
		this.pvreunions = pvreunions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projet")
	public Set<Contratsociete> getContratsocietes() {
		return this.contratsocietes;
	}

	public void setContratsocietes(Set<Contratsociete> contratsocietes) {
		this.contratsocietes = contratsocietes;
	}

}
