package com.mit.entity;

// Generated 9 juin 2016 18:19:25 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Societe generated by hbm2java
 */
@Entity
@Table(name = "societe", catalog = "mitdb")
public class Societe implements java.io.Serializable {

	private Integer idSociete;
	private String nomSociete;
	private String adrSociete;
	private Long telSociete;
	private String emailSociete;
	private Set<Contratsociete> contratsocietes = new HashSet<Contratsociete>(0);

	public Societe() {
	}

	public Societe(String nomSociete, String adrSociete, Long telSociete,
			String emailSociete, Set<Contratsociete> contratsocietes) {
		this.nomSociete = nomSociete;
		this.adrSociete = adrSociete;
		this.telSociete = telSociete;
		this.emailSociete = emailSociete;
		this.contratsocietes = contratsocietes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idSociete", unique = true, nullable = false)
	public Integer getIdSociete() {
		return this.idSociete;
	}

	public void setIdSociete(Integer idSociete) {
		this.idSociete = idSociete;
	}

	@Column(name = "nomSociete", length = 254)
	public String getNomSociete() {
		return this.nomSociete;
	}

	public void setNomSociete(String nomSociete) {
		this.nomSociete = nomSociete;
	}

	@Column(name = "adrSociete", length = 254)
	public String getAdrSociete() {
		return this.adrSociete;
	}

	public void setAdrSociete(String adrSociete) {
		this.adrSociete = adrSociete;
	}

	@Column(name = "telSociete")
	public Long getTelSociete() {
		return this.telSociete;
	}

	public void setTelSociete(Long telSociete) {
		this.telSociete = telSociete;
	}

	@Column(name = "emailSociete", length = 254)
	public String getEmailSociete() {
		return this.emailSociete;
	}

	public void setEmailSociete(String emailSociete) {
		this.emailSociete = emailSociete;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "societe")
	public Set<Contratsociete> getContratsocietes() {
		return this.contratsocietes;
	}

	public void setContratsocietes(Set<Contratsociete> contratsocietes) {
		this.contratsocietes = contratsocietes;
	}

}
